<?php
class dinpayalipay{
	function __construct($config = array()){
		$this->config = $config;
		$this->pass    = $config['pass'];//密钥
		$this->mid     = $config['mid'];//商户编号
		$this->respond = $config['respond'];//callbackurl
	}


	/**
	 * 生成支付代码
	 * @param   array   $order      订单信息
	 * @param   array   $payment    支付方式信息
	 */
	function get_code($order,$configs,$host){
		//$configs['returnbackurl'] = $configs['hrefbackurl'] = $host;
		$pic = __ROOT__."/dinpaycodeimg/".$order['trano'].".png";
		if(is_file($pic) && $order['state']==0){
			$html = '';
			$html .= "<center>请使用支付宝扫描下面的二维支付码1</center><br>";
			$html .= "<center><img src='".ltrim($pic,'.')."'></center>";
			return $html;
			exit;
		}

		$aa = include ('./dinpayalipay/phpqrcode.php');

		/* *
         *功能：智付微信支付接口
         *版本：3.0
         *日期：2016-07-10
         *说明：
         *以下代码只是为了方便商户测试而提供的样例代码，商户可以根据自己网站的需要，按照技术文档编写,
         *并非一定要使用该代码。该代码仅供学习和研究智付接口使用，仅为提供一个参考。
         **/


///////////////////////////  初始化接口参数  //////////////////////////////
		/**
		接口参数请参考智付微信支付文档，除了sign参数，其他参数都要在这里初始化
		 */
		include_once("./dinpayalipay/merchant.php");

		$merchant_code = "1000210688";//商户号，1118004517是测试商户号，调试时要更换商家自己的商户号
		//$merchant_code = "1118004517";

		$service_type = "alipay_scan";

		$notify_url = $configs['returnbackurl'].'/Payback.dinpayalipay';	//异步地址

		$interface_version ="V3.3";

		$sign_type = "RSA-S";

		$client_ip = get_client_ip(); 
		
		$order_no = $order['trano'];

		$order_time = date('Y-m-d H:i:s', $order['oddtime']);

		$order_amount ='0.01';
		/*
        $order_no = date('YmdHis');
        $order_time = date('Y-m-d H:i:s');
        //$order_amount = '0.1';
        */

		$product_name = "shoes";

		$product_code = "";

		$product_num = "";

		$product_desc = "";

		$extra_return_param = "";

		$extend_param = "";

/////////////////////////////   参数组装  /////////////////////////////////
		/**
		除了sign_type dinpaySign参数，其他非空参数都要参与组装，组装顺序是按照a~z的顺序，下划线"_"优先于字母
		 */

		$signStr = "";
		$signStr = $signStr."client_ip=".$client_ip."&";

		if($extend_param != ""){
			$signStr = $signStr."extend_param=".$extend_param."&";
		}

		if($extra_return_param != ""){
			$signStr = $signStr."extra_return_param=".$extra_return_param."&";
		}

		$signStr = $signStr."interface_version=".$interface_version."&";

		$signStr = $signStr."merchant_code=".$merchant_code."&";

		$signStr = $signStr."notify_url=".$notify_url."&";

		$signStr = $signStr."order_amount=".$order_amount."&";

		$signStr = $signStr."order_no=".$order_no."&";

		$signStr = $signStr."order_time=".$order_time."&";

		if($product_code != ""){
			$signStr = $signStr."product_code=".$product_code."&";
		}

		if($product_desc != ""){
			$signStr = $signStr."product_desc=".$product_desc."&";
		}

		$signStr = $signStr."product_name=".$product_name."&";

		if($product_num != ""){
			$signStr = $signStr."product_num=".$product_num."&";
		}

		$signStr = $signStr."service_type=".$service_type;

/////////////////////////////   RSA-S签名  /////////////////////////////////



/////////////////////////////////初始化商户私钥//////////////////////////////////////

//商家私钥，由RSA-S密钥对生成工具生成(merchant private key,generated by the key pair generate tools for RSA-S)
		$merchant_private_key= '-----BEGIN PRIVATE KEY-----
MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMAeYc78jfe85tmZ
ql8psc6BFRwfENq8kmmuqFbD4MJ2f+AXF1c81VALTphJXUJJuY2Not61VeLd44QB
j/id4vKLux4j5olITrf9E5jwaSZmjwDFLpGv3zj4mqEZ2Z90BL/8u8PmSJ3EVaiU
V8SOYY+4lLegjOcnLdsLIXAI7LZHAgMBAAECgYEAjzjXH7DFwW9xBb159pGlvVYb
v6glL3wvBlwvoOdL8ozWzd9JBj8SoyaaxArFXHqLusxhI/g5e/SA/VMQ2n4Rxgap
EzF+MPqZgTLyVQEVGdT1vUJUDTNk/Y4wtPEDtJ1JalgCdynm77j5XiDHy23fOyFM
7JOY0uhPz9rLJgHk9ykCQQDlx29OtGtZnxrlyDMKkZr5pkqjbo6REkENTaHcZlNZ
AyFvAa8SfIXGJFoqOxBPpx/ZDf1mh88JIAcmrafFqPzbAkEA1grFKsEPmPCOeZGv
Sg1flCA0b7i7OmnOSxqC1ABqwhz/x+EEa25FrH+qrQDqmrGGLRXSP5EVMrifbFyY
58cyBQJAKu27qeSjObcz+0IP5yWU4pdi0m3RTOEwLiAW4Wpsn/CpymdyIe4JwB8C
iWlHftomZRLsCL/OulG1hFBlS9RqiQJAF0omuAc3xkFuj0XN1/Xqj3iNnBZysOFw
Y/WnhJ/i/eof3sTaMUJXbHSbwqVV4a0tV1yHewkzUEiMeEL/FEE1bQJBAKyj6W7a
0gqs6vopOHQu0bZzPd095XKF194501Sr3sDckiqcflOHE7x3O75Zr6iK6XMUstYl
ijzEJHBwC/j/kWM=
-----END PRIVATE KEY-----';

//智付公钥，每个商家对应一个固定的智付公钥，即为商家后台"公钥管理"->"智付公钥"里的内容
//Dinpay public key,every merchant has a unique Dinpay public key,you can find it on our merchant system,Pay Management - > Public Key - >Dinpay Public Key.
		$pubKey = 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAHmHO/I33vObZmapfKbHOgRUc
HxDavJJprqhWw+DCdn/gFxdXPNVQC06YSV1CSbmNjaLetVXi3eOEAY/4neLyi7se
I+aJSE63/ROY8GkmZo8AxS6Rr984+JqhGdmfdAS//LvD5kidxFWolFfEjmGPuJS3
oIznJy3bCyFwCOy2RwIDAQAB';


		$merchant_private_key= openssl_get_privatekey($merchant_private_key);
//		$merchant_private_key= openssl_get_privatekey($merchant_private_key);

		openssl_sign($signStr,$sign_info,$merchant_private_key,OPENSSL_ALGO_MD5);

		$sign = base64_encode($sign_info);
		//dump($sign);

/////////////////////////  提交参数到智付微信网关  ////////////////////////
		/**
		curl方法提交支付参数到智付微信网关https://api.dinpay.com/gateway/api/weixin，并且获取返回值
		 */


		$postdata=array('extend_param'=>$extend_param,
			'extra_return_param'=>$extra_return_param,
			'product_code'=>$product_code,
			'product_desc'=>$product_desc,
			'product_num'=>$product_num,
			'merchant_code'=>$merchant_code,
			'service_type'=>$service_type,
			'notify_url'=>$notify_url,
			'interface_version'=>$interface_version,
			'sign_type'=>$sign_type,
			'order_no'=>$order_no,
			'client_ip'=>$client_ip,
			'sign'=>$sign,
			'order_time'=>$order_time,
			'order_amount'=>$order_amount,
			'product_name'=>$product_name);

		$ch = curl_init();
		curl_setopt($ch,CURLOPT_URL,"https://api.ddbill.com/gateway/api/scanpay");
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
		curl_setopt($ch, CURLOPT_POST, true);
		curl_setopt($ch, CURLOPT_HEADER, false);
		curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($postdata));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		$response=curl_exec($ch);
		$res=simplexml_load_string($response);
		 dump($postdata); 
		 dump($res); 
		curl_close($ch);


/////////////////////////////   获取qrcode，并生成二维码  /////////////////////
		/**
		解析智付返回参数，获取qrcode的值，并且根据这个值生成二维码
		 */

		$resp_code=$res->response->resp_code;
		if($resp_code=="SUCCESS"){

			$qrcode=$res->response->qrcode;

			if(file_exists('qrcode.png')){

				unlink('qrcode.png');
			}
			$pic ="./dinpaycodeimg/".$order_no.".png";
			;
			//$pic = 'weixin://wxpay/bizpayurl?pr=M3Xl19z';

			$errorCorrectionLevel = 'L';

			$matrixPointSize = 10;
//			$QRcode = new \QRcode();
//			$QRcode->png ($qrcode, "'.$pic.'", $errorCorrectionLevel, $matrixPointSize, 2 );
			QRcode::png ( $qrcode, $pic, $errorCorrectionLevel, $matrixPointSize, 2 );
			$html = '';
			$html .= "<center>请使用用支付宝扫描下面的二维支付码</center><br>";
			//$returnhtml = "<p style='color:red'>平台官方微信支付暂未开通，下面为测试二维码，请勿扫描支付</p><br>";
			$html .= "<center><img src='".ltrim($pic,'.')."'></center>";
			return $html;

		}else{
			return '支付宝扫二维码获取失败';

		}


	}

	/**
	 * 响应操作
	 */

	function respond($request){
		$payinfo = M('payset')->where(array('type'=>'dinpay'))->find();
		$_config = array_filter(array_unique(explode(PHP_EOL,$payinfo['config'])));
		foreach($_config as $k=>$v){
			$array = array();
			$array = explode('###',$v);
			$configs[trim($array[0])] = trim($array[1]);
		}
		$merchant_id    = $configs['mid'];       // 获取商户编号
		$merchant_key   = $configs['pass'];           // 获取秘钥

		//获取智付的反馈参数
		$OrderInfo      = $_POST['OrderMessage'];
		$signMsgs       = $_POST['Digest'];
		//验签
		$digest = strtoupper(md5($OrderInfo.$merchant_key));

		//验证成功
		if ($digest == $signMsgs){
			$string='';
			for ($i=0;$i<strlen($OrderInfo)-1;$i+=2)
				$string.=chr(hexdec($OrderInfo[$i].$OrderInfo[$i+1]));
			$OrderInfo =$string;
			$parm=explode("|", $OrderInfo);

			$paymentId =$parm[1];
			$money=$parm[2];

			$m_id		= 	$parm[0];
			$m_orderid	= 	$parm[1];
			$m_oamount	= 	$parm[2];
			$m_ocurrency= 	$parm[3];
			$m_language	= 	$parm[4];
			$s_name		= 	$parm[5];
			$s_addr		= 	$parm[6];
			$s_postcode	= 	$parm[7];
			$s_tel		= 	$parm[8];
			$s_eml		= 	$parm[9];
			$r_name		= 	$parm[10];
			$r_addr		= 	$parm[11];
			$r_postcode	= 	$parm[12];
			$r_tel		= 	$parm[13];
			$r_eml		= 	$parm[14];
			$m_ocomment	= 	$parm[15];
			$modate		=	$parm[16];
			$State		=	$parm[17];

			$c_memo2        = trim($_REQUEST['c_memo2']);
			//判断是否是会员充值订单

			$accountinfo = M('payaccount')->where("paytype='dinpay' and status=0 and trano='{$m_orderid}'")->find();
			if(!$accountinfo){
				return false;
			}
			if ($State == 2){
				$isok = paysetok($accountinfo['uid'],$accountinfo['id'],$accountinfo['amount']);
				return $isok;
			}else{
				return false;
			}

		}
	}
}

?>