<?php
class dinpay{
	function get_code($order,$configs,$host,$webhost){ 
		   
		//$configs['returnbackurl'] = $configs['hrefbackurl'] = $host;
//商家私钥，由RSA-S密钥对生成工具生成(merchant private key,generated by the key pair generate tools for RSA-S)
		$priKey= '-----BEGIN PRIVATE KEY-----
MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMAeYc78jfe85tmZ
ql8psc6BFRwfENq8kmmuqFbD4MJ2f+AXF1c81VALTphJXUJJuY2Not61VeLd44QB
j/id4vKLux4j5olITrf9E5jwaSZmjwDFLpGv3zj4mqEZ2Z90BL/8u8PmSJ3EVaiU
V8SOYY+4lLegjOcnLdsLIXAI7LZHAgMBAAECgYEAjzjXH7DFwW9xBb159pGlvVYb
v6glL3wvBlwvoOdL8ozWzd9JBj8SoyaaxArFXHqLusxhI/g5e/SA/VMQ2n4Rxgap
EzF+MPqZgTLyVQEVGdT1vUJUDTNk/Y4wtPEDtJ1JalgCdynm77j5XiDHy23fOyFM
7JOY0uhPz9rLJgHk9ykCQQDlx29OtGtZnxrlyDMKkZr5pkqjbo6REkENTaHcZlNZ
AyFvAa8SfIXGJFoqOxBPpx/ZDf1mh88JIAcmrafFqPzbAkEA1grFKsEPmPCOeZGv
Sg1flCA0b7i7OmnOSxqC1ABqwhz/x+EEa25FrH+qrQDqmrGGLRXSP5EVMrifbFyY
58cyBQJAKu27qeSjObcz+0IP5yWU4pdi0m3RTOEwLiAW4Wpsn/CpymdyIe4JwB8C
iWlHftomZRLsCL/OulG1hFBlS9RqiQJAF0omuAc3xkFuj0XN1/Xqj3iNnBZysOFw
Y/WnhJ/i/eof3sTaMUJXbHSbwqVV4a0tV1yHewkzUEiMeEL/FEE1bQJBAKyj6W7a
0gqs6vopOHQu0bZzPd095XKF194501Sr3sDckiqcflOHE7x3O75Zr6iK6XMUstYl
ijzEJHBwC/j/kWM=
-----END PRIVATE KEY-----';

//智付公钥，每个商家对应一个固定的智付公钥，即为商家后台"公钥管理"->"智付公钥"里的内容
//Dinpay public key,every merchant has a unique Dinpay public key,you can find it on our merchant system,Pay Management - > Public Key - >Dinpay Public Key.
		$pubKey = 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAHmHO/I33vObZmapfKbHOgRUc
HxDavJJprqhWw+DCdn/gFxdXPNVQC06YSV1CSbmNjaLetVXi3eOEAY/4neLyi7se
I+aJSE63/ROY8GkmZo8AxS6Rr984+JqhGdmfdAS//LvD5kidxFWolFfEjmGPuJS3
oIznJy3bCyFwCOy2RwIDAQAB';

		$priKey= openssl_get_privatekey($priKey);

		/////////////////////////////////初始化提交参数//////////////////////////////////////
		////////////////////////initial the parameter datas/////////////////////////////////

		$merchant_code = "1000210688";

		$service_type ="direct_pay";

		$interface_version ="V3.0";

		$pay_type = "";

		$sign_type ="RSA-S";

		$input_charset = "UTF-8";

		$order_no = $order['trano'];

		$order_time = date('Y-m-d H:i:s', $order['oddtime']);

  		$order_amount =$order['amount'];

		$product_name ="testpay";

		$product_code = "";

		$product_desc = "";

		$product_num = "";

		$show_url = "";

		$client_ip ="" ;

		$bank_code = "";

		$redo_flag = "";

		$extend_param = "";

		$extra_return_param = "";

		$notify_url = $configs['returnbackurl'].'/Payback.dinpay';	//异步地址 
     
		     $return_url = $host.'/Account.dealRecord.do';	//前台地址 


		/////////////////////////////   数据签名  /////////////////////////////////
		////////////////////////////  Data signature  ////////////////////////////

		/**
		签名规则定义如下：
		（1）参数列表中，除去sign_type、sign两个参数外，其它所有非空的参数都要参与签名，值为空的参数不用参与签名；
		（2）签名顺序按照参数名a到z的顺序排序，若遇到相同首字母，则看第二个字母，以此类推，同时将商家支付密钥key放在最后参与签名，组成规则如下：
		参数名1=参数值1&参数名2=参数值2&……&参数名n=参数值n&key=key值
		 */

		/**
		The definition of signature rule is as follows :
		（1） In the list of parameters, except the two parameters of sign_type and sign, all the other parameters that are not in blank shall be signed, the parameter with value as blank doesn't need to be signed;
		（2） The sequence of signature shall be in the sequence of parameter name from a to z, in case of same first letter, then in accordance with the second letter, so on so forth, meanwhile, the merchant payment key shall be put at last for signature, and the composition rule is as follows :
		Parameter name 1 = parameter value 1& parameter name 2 = parameter value 2& ......& parameter name N = parameter value N & key = key value
		 */

		$signStr= "";

		if($bank_code != ""){
			$signStr = $signStr."bank_code=".$bank_code."&";
		}
		if($client_ip != ""){
			$signStr = $signStr."client_ip=".$client_ip."&";
		}
		if($extend_param != ""){
			$signStr = $signStr."extend_param=".$extend_param."&";
		}
		if($extra_return_param != ""){
			$signStr = $signStr."extra_return_param=".$extra_return_param."&";
		}

		$signStr = $signStr."input_charset=".$input_charset."&";
		$signStr = $signStr."interface_version=".$interface_version."&";
		$signStr = $signStr."merchant_code=".$merchant_code."&";
		$signStr = $signStr."notify_url=".$notify_url."&";
		$signStr = $signStr."order_amount=".$order_amount."&";
		$signStr = $signStr."order_no=".$order_no."&";
		$signStr = $signStr."order_time=".$order_time."&";

		if($pay_type != ""){
			$signStr = $signStr."pay_type=".$pay_type."&";
		}

		if($product_code != ""){
			$signStr = $signStr."product_code=".$product_code."&";
		}
		if($product_desc != ""){
			$signStr = $signStr."product_desc=".$product_desc."&";
		}

		$signStr = $signStr."product_name=".$product_name."&";

		if($product_num != ""){
			$signStr = $signStr."product_num=".$product_num."&";
		}
		if($redo_flag != ""){
			$signStr = $signStr."redo_flag=".$redo_flag."&";
		}
		if($return_url != ""){
			$signStr = $signStr."return_url=".$return_url."&";
		}

		if($show_url != ""){

			$signStr = $signStr."service_type=".$service_type."&";
			$signStr = $signStr."show_url=".$show_url;
		}else{

			$signStr = $signStr."service_type=".$service_type;
		}
		//dump(function_exists( 'openssl_sign' ));exit;
		openssl_sign($signStr,$sign_info,$priKey,OPENSSL_ALGO_MD5);
		//dump($signStr);exit;

		$sign = base64_encode($sign_info);
		$html = '';
		$html .= '<form name="dinpayForm" method="post" action="https://pay.ddbill.com/gateway?input_charset=UTF-8" target="_self" target="_blank">';
		$html .= '<input type="hidden" name="sign"		  value="'.$sign.'" />';
		$html .= '<input type="hidden" name="merchant_code" value="'.$merchant_code.'" />';
		$html .= '<input type="hidden" name="bank_code"     value="'.$bank_code.'"/>';
		$html .= '<input type="hidden" name="order_no"      value="'.$order_no.'"/>';
		$html .= '<input type="hidden" name="order_amount"  value="'.$order_amount.'"/>';
		$html .= '<input type="hidden" name="service_type"  value="'.$service_type.'"/>';
		$html .= '<input type="hidden" name="input_charset" value="'.$input_charset.'"/>';
		$html .= '<input type="hidden" name="notify_url"    value="'.$notify_url.'">';
		$html .= '<input type="hidden" name="interface_version" value="'.$interface_version.'"/>';
		$html .= '<input type="hidden" name="sign_type"     value="'.$sign_type.'"/>';
		$html .= '<input type="hidden" name="order_time"    value="'.$order_time.'"/>';
		$html .= '<input type="hidden" name="product_name"  value="'.$product_name.'"/>';
		$html .= '<input Type="hidden" Name="client_ip"     value="'.$client_ip.'"/>';
		$html .= '<input Type="hidden" Name="extend_param"  value="'.$extend_param.'"/>';
		$html .= '<input Type="hidden" Name="extra_return_param" value="'.$extra_return_param.'"/>';
		$html .= '<input Type="hidden" Name="pay_type"  value="'.$pay_type.'"/>';
		$html .= '<input Type="hidden" Name="product_code"  value="'.$product_code.'"/>';
		$html .= '<input Type="hidden" Name="product_desc"  value="'.$product_desc.'"/>';
		$html .= '<input Type="hidden" Name="product_num"   value="'.$product_num.'"/>';
		$html .= '<input Type="hidden" Name="return_url"    value="'.$return_url.'"/>';
		$html .= '<input Type="hidden" Name="show_url"      value="'.$show_url.'"/>';
		$html .= '<input Type="hidden" Name="redo_flag"     value="'.$redo_flag.'"/>';
		$html .= '</form>';
		$html .= '</body></html>';
 		 $html .= "<script>document.forms['dinpayForm'].submit();</script>";
		return $html;
	}

}

?>